# Generated by Django 2.0.4 on 2018-04-16 13:53

from django.db import migrations, models
import django.db.models.deletion
import travellog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('text', models.TextField(blank=True)),
                ('date', models.TextField(blank=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zoom', models.FloatField(default=12.5)),
                ('bearing', models.PositiveSmallIntegerField(default=0)),
                ('pitch', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(max_length=1000, upload_to=travellog.models.Photo._photo_upload_path_callback)),
                ('size', models.CharField(choices=[('1x1', '1x1'), ('1x2', '1x2'), ('2x1', '2x1'), ('2x2', '2x2'), ('3x1', '3x1'), ('3x2', '3x2'), ('3x3', '3x3')], default='1x1', max_length=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='travellog.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.TextField(default='map-us-ca')),
                ('title', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TravelLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('slug', models.SlugField()),
                ('text', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='travellog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='travellog.TravelLog'),
        ),
        migrations.AddField(
            model_name='location',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='travellog.Section'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='section',
            order_with_respect_to='travellog',
        ),
        migrations.AlterOrderWithRespectTo(
            name='photo',
            order_with_respect_to='location',
        ),
        migrations.AlterOrderWithRespectTo(
            name='location',
            order_with_respect_to='section',
        ),
    ]
